[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=100µm_2000fps_30degC_5
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=2000
Shuttertime=234
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=17.11.2017 14:35:09
ImageCount=1321
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=1321
TriggerFrameNumber_00=-79
TriggerRefTime_00=5231,80448
