[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=FR_100µm_2000fps_20degC_8
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=525
Shuttertime=70
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=21.11.2017 12:59:13
ImageCount=421
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=421
TriggerFrameNumber_00=1
TriggerRefTime_00=30423,28128
