[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=100µm_2000fps_60degC_2
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=2000
Shuttertime=50
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=14.11.2017 14:50:15
ImageCount=651
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=651
TriggerFrameNumber_00=-349
TriggerRefTime_00=2596,608
