[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=100µm_2000fps_80degC_3
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=2000
Shuttertime=50
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=14.11.2017 15:23:52
ImageCount=301
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=301
TriggerFrameNumber_00=-149
TriggerRefTime_00=5870,91008
