[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=Fr_100µm_2000fps_20degC_5
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=2000
Shuttertime=234
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=17.11.2017 13:52:39
ImageCount=1081
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=1081
TriggerFrameNumber_00=-119
TriggerRefTime_00=2368,47744
