[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=100µm_2000fps_60degC_3
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=2000
Shuttertime=50
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=14.11.2017 14:54:37
ImageCount=566
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=566
TriggerFrameNumber_00=-184
TriggerRefTime_00=31655,84576
