[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=101nl_50N_1300µs_Substrat
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=1000
Shuttertime=50
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=08.11.2017 16:50:34
ImageCount=301
[IMAGEDESCRIPTION]
ImageWidth=1024
ImageHeight=1428
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=301
TriggerFrameNumber_00=985
TriggerRefTime_00=870402,11552
