[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=avi
Name=Fr_100µm_2000fps_20degC_6
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=525
Shuttertime=70
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=21.11.2017 11:42:18
ImageCount=341
[IMAGEDESCRIPTION]
ImageWidth=432
ImageHeight=938
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=341
TriggerFrameNumber_00=-79
TriggerRefTime_00=21560,65632
